imports:
  # publisher types
  - { resource: "publisher.type.yml" }

  # exchanges available
  - { resource: "publisher.exchange.yml" }

services:
  amqp.config.loader:
    class: \Amqp\Base\Config\YamlConfigLoader
    arguments:
      - %config_path%/config.yml

  amqp.config.factory:
    class: \Amqp\Base\Config\Processor
    arguments:
      - @amqp.config.loader

  amqp.builder.factory:
    class: \Amqp\Builder
    arguments:
      - @amqp.config.factory

  # general listener configuration
  publisher.config.loader:
    class: \Amqp\Base\Config\YamlConfigLoader
    arguments:
      - %config_path%/publisher.yml

  publisher.config.factory:
    class: \Amqp\Base\Config\Processor
    arguments:
      - @publisher.config.loader

  publisher.builder:
    class: \Amqp\Util\Factory\Publisher
    arguments:
      - @publisher.config.factory

