listener:
  listener:
    consumer-test:
      # the queue on which we need to listen for incoming messages
      queue:                test-queue

      # behavior on failed process. Can be one of: requeue, error, stop, continue
      # requeue: nack and requeue the message. continue listening after the operation
      # error: nack the message without requeuing. continue listening after the operation
      # stop: nack the message and stop the current listener with exit code 1
      # continue: ack the message and continue listening.
      onProcessError:

        # bad request: something happened with the message before it arrived at the application. for example something
        # happened in the transformation layer
        err_bad_request:            error

        # there is no entity (processor) capable of processing the current entity. No processor for this type
        # of message could be found.
        err_not_found:              continue

        # the processing reached application level, but something happened in there (for example a failed mysql)
        crit_internal_server_error: error

        # the message reached the application layer, but the application is unable to process the message
        crit_not_implemented:       error

      # if on processing we get an error, how many times we will requeue the message before not requeing it anymore
      maxRequeue:           3

      # bulk ack: the messages will only be acknowledged when the bulkack number has been hit
      bulkAck:              50